In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
numpy.__version__

'1.23.4'

In [4]:
import numpy as np

# Упражнения по библиотеке Numpy

# 1. Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [5]:
a = np.arange(11)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# 2. Заменить максимальный элемент случайного массива на 0

In [6]:
a = np.random.random(15)


In [7]:
print(a)

[0.00872689 0.51581119 0.5246025  0.7784689  0.43004311 0.5040156
 0.62026655 0.81354775 0.20096151 0.36480415 0.8478412  0.73807009
 0.39444006 0.4921068  0.80155099]


In [8]:
a[a.argmax()] = 0
print(a)

[0.00872689 0.51581119 0.5246025  0.7784689  0.43004311 0.5040156
 0.62026655 0.81354775 0.20096151 0.36480415 0.         0.73807009
 0.39444006 0.4921068  0.80155099]


# 3. Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [9]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


# 4. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [10]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

d = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(d.any((3,1)).all(1))[0]
print(rows)

[3 4 5 6 7]


# 5. Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [11]:
a = np.random.randint(0,5,(10,3))
print(a)

b = np.all(a[:,1:] == a[:,:-1], axis=1)
c = a[~b]
print(c)

c = a[a.max(axis=1) != a.min(axis=1),:]
print(c)


[[0 0 3]
 [3 0 3]
 [1 1 1]
 [1 1 0]
 [0 1 0]
 [1 0 1]
 [2 4 0]
 [4 3 4]
 [1 0 0]
 [0 4 0]]
[[0 0 3]
 [3 0 3]
 [1 1 0]
 [0 1 0]
 [1 0 1]
 [2 4 0]
 [4 3 4]
 [1 0 0]
 [0 4 0]]
[[0 0 3]
 [3 0 3]
 [1 1 0]
 [0 1 0]
 [1 0 1]
 [2 4 0]
 [4 3 4]
 [1 0 0]
 [0 4 0]]


# 6. Дан двумерный массив. Удалить те строки, которые повторяются

In [12]:
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

# задача 1 

In [13]:
x = np.array([[1,0,1],[2,0,2],[3,0,3],[4,4,4]])
print(x)

[[1 0 1]
 [2 0 2]
 [3 0 3]
 [4 4 4]]


In [14]:

np.prod(np.diag(x)[np.diag(x)!=0]  )

3

# задача 2

In [15]:
import numpy as np

In [16]:
x = np.array([1,2,2,4])
y = np.array([4,2,1,2])

mult = np.isin(x, y)

In [17]:
mult

array([ True,  True,  True,  True])

# задача 3

In [18]:
x = np.array([6,2,0,3,0,0,5,7,0])
null = x == 0
print (x[1:][null[:-1]].max())

5


# задача 4 

In [19]:
 a = [2,2,2,3,3,3,5]

In [20]:
import numpy as np

def encode(a):
    #YOUR CODE
    elements=[]
    counts=[]
    count=1
    for i in range(len(a)):
        if(i==len(a)-1):
            elements.append(a[i])
            counts.append(count)
            break
            
        
        if(a[i]==a[i+1]):
            count+=1
        else:
                elements.append(a[i])
                counts.append(count)
                count=1
    x=np.array(elements)
    s=np.array(counts)

    result = (x,s)
    return result

# задача 5

In [21]:
import numpy as np

p1 = np.array((1, 2, 3))
p2 = np.array((4, 5, 6))

In [22]:
import math
distance = math.dist(p1, p2)
print(distance)

5.196152422706632


In [23]:
import numpy as np

p1 = np.array((1, 2, 3))
p2 = np.array((4, 5, 6))

In [24]:
distance = np.sqrt(np.dot(p1-p2, p1-p2))
print(distance)

5.196152422706632
